<?php

/*
Template Name: Home
*/

get_template_part('partials/head');
get_header();
echo '<div class="js-site site">';
echo '<section style="background-image:url(' . get_bloginfo('template_directory') . '/images/img-3.jpg);" class="js-parallax island--cover island flush--bottom border--bottom js-header">';
	echo '<div class="centered--v--h soft--left row">';
		echo '<div class="grid">';
			echo '<div class="grid__item one-half">';
				echo '<h1 class="giga">The grand bold statement</h1>';
				echo '<h2 class="gamma">Furthermore, aenean nibh lorem, consequat congue <br/>lorem ipsum dolor sit amet</h2>';
				echo '<a class="btn btn--large ">Order Now</a>';
			echo '</div>';	
		echo '</div>';	
	echo '</div>';	
	echo '<span class="icon-play play-indicator"></span>';
	echo '<span class="icon-angle-down scroll-indicator"></span>';
echo '</section>';

echo '<section class=" border--bottom soft--left soft--right">';
	echo '<div class="row ">';
		echo '<div class="grid">';
			echo '<div class="grid__item soft--top--4 three-eighths">';
				echo '<h2 class="strong">Effortless, right out of the box</h2>';
				echo '<p class="lead">No programming required, comes highly intelligent and fully house trained, no coddling neccessary.</p>';
			echo '</div>';
			echo '<div class="grid__item four-eighths push--one-eighth">';
				echo '<img class="img--block" src="http://placehold.it/800x500&text=image+that+demos+ease+of+startup" />';
			echo '</div>';
		echo '</div>';
	echo '</div>';
echo '</section>';
echo '<section class="islet bg--grey-lightest border--bottom">';
	echo '<div class="row">';
		echo '<div class="grid">';
			echo '<div class="grid__item one-tenth push--two-tenths">';
				echo '<img class="img--circle" src="http://placehold.it/60x60" />';
			echo '</div>';
			echo '<div class="grid__item push--two-tenths five-tenths">';
				echo '<blockquote><p>Aenean nibh lorem, consequat congue lorem ipsum dolor sit amet, consectetur adipiscing elit. In faucibus augue massa, vitae rhoncus urna rhoncus ac.</p></blockquote>';
				echo '<p class="flush--bottom">Dwell Magazine</p>';
				echo '<h5><a href="#">View All Testimonials</a></h5>';
			echo '</div>';
		echo '</div>';
	echo '</div>';		
echo '</section>';

echo '<section class=" border--bottom soft--left soft--right">';
	echo '<div class="row ">';
		echo '<div class="grid">';
			echo '<div class="grid__item four-eighths ">';
				echo '<img class="img--block" src="http://placehold.it/800x500&text=image+that+demos+remote+sensors+everyone+comfortable" />';
			echo '</div>';
			echo '<div class="grid__item soft--top--4 push--one-eighth three-eighths">';
				echo '<h2 class="strong">Master of the micro-climates</h2>';
				echo '<p class="lead">Ecobee’s remote sensor ensures that the most important room in your house is at the right temperature at the right time.</p>';
			echo '</div>';
		echo '</div>';
	echo '</div>';
echo '</section>';

echo '<section class="islet bg--grey-lightest border--bottom">';
	echo '<div class="row">';
		echo '<div class="grid">';
			echo '<div class="grid__item one-tenth push--two-tenths">';
				echo '<img class="img--circle" src="http://placehold.it/60x60" />';
			echo '</div>';
			echo '<div class="grid__item push--two-tenths five-tenths">';
				echo '<blockquote><p>Elit massa vestibulum lacus nullam non nulla justo. Etiam sollicitudin ipsum sed odio porta, in interdum sem congue. Vivamus laoreet, mauris non!</p></blockquote>';
				echo '<p class="flush--bottom">Home Building Expert</p>';
				echo '<h5><a href="#">View All Testimonials</a></h5>';
			echo '</div>';
		echo '</div>';
	echo '</div>';		
echo '</section>';

echo '<section class=" border--bottom soft--left soft--right">';
	echo '<div class="row ">';
		echo '<div class="grid">';
			echo '<div class="grid__item soft--top--4 three-eighths">';
				echo '<h2 class="strong">A great investment</h2>';
				echo '<p class="lead">You will save an average of 23% of your heating and cooling bills, which will pay for your ecobee year-after-year.</p>';
			echo '</div>';
			echo '<div class="grid__item four-eighths push--one-eighth">';
				echo '<img class="img--block" src="http://placehold.it/800x500&text=image+that+demos+energy+savings" />';
			echo '</div>';
		echo '</div>';
	echo '</div>';
echo '</section>';
echo '<section class="islet bg--grey-lightest  border--bottom">';
	echo '<div class="row">';
		echo '<div class="grid">';
			echo '<div class="grid__item one-tenth push--two-tenths">';
				echo '<img class="img--circle" src="http://placehold.it/60x60" />';
			echo '</div>';
			echo '<div class="grid__item push--two-tenths five-tenths">';
				echo '<blockquote><p>Proin semper odio tellus, et suscipit massa malesuada sed. Nullam non nulla justo. Etiam sollicitudin ipsum sed odio porta, in interdum sem congue. Suspendisse justo nunc!</p></blockquote>';
				echo '<p class="flush--bottom">Amanda Bradley, Toronto ON</p>';
				echo '<h5><a href="#">View All Testimonials</a></h5>';
			echo '</div>';
		echo '</div>';
	echo '</div>';		
echo '</section>';


echo '<section class=" border--bottom soft--left soft--right">';
	echo '<div class="row ">';
		echo '<div class="grid">';
			echo '<div class="grid__item four-eighths ">';
				echo '<img class="img--block" src="http://placehold.it/800x500&text=image+that+demos+reliable+power+source"  />';
			echo '</div>';
			echo '<div class="grid__item soft--top--4 push--one-eighth three-eighths">';
				echo '<h2 class="strong">A very helpful house guest</h2>';
				echo '<p class="lead">Ecobee&rsquo;s Power Adapter kit means you never have to think twice about battery replacement or lorem ipsum dolar sit.</p>';
			echo '</div>';
		echo '</div>';
	echo '</div>';
echo '</section>';

echo '<section class="islet bg--grey-lightest border--bottom">';
	echo '<div class="row">';
		echo '<div class="grid">';
			echo '<div class="grid__item one-tenth push--two-tenths">';
				echo '<img class="img--circle" src="http://placehold.it/60x60" />';
			echo '</div>';
			echo '<div class="grid__item push--two-tenths five-tenths">';
				echo '<blockquote><p>Elit massa vestibulum lacus nullam non nulla justo. Etiam sollicitudin ipsum sed odio porta, in interdum sem congue. Vivamus laoreet, mauris non!</p></blockquote>';
				echo '<p class="flush--bottom">Home Building Expert</p>';
				echo '<h5><a href="#">View All Testimonials</a></h5>';
			echo '</div>';
		echo '</div>';
	echo '</div>';		
echo '</section>';


echo '<div id="slides">';
	echo '<ul class="slides-container">';
    	echo '<li>';
      		echo '<img src="' . get_bloginfo('template_directory') . '/images/img-1.jpg" alt="">';
      		echo '<div class="centered--v--h soft--left row">';
				echo '<div class="grid">';
					echo '<div class="grid__item one-half">';
						echo '<h1 class="giga">Get your app</h1>';
						echo '<h2 class="gamma">Furthermore, aenean nibh lorem, consequat congue <br/>lorem ipsum dolor sit amet</h2>';
						echo '<a class="btn" href="#">Apple Store</a> <a class="btn" href="#">Android Store</a>';
					echo '</div>';	
				echo '</div>';	
			echo '</div>';	
    	echo '</li>';
    	echo '<li>';
      		echo '<img src="' . get_bloginfo('template_directory') . '/images/img-2.jpg" alt="">';
      		echo '<div class="centered--v--h soft--left row">';
				echo '<div class="grid">';
					echo '<div class="grid__item push--one-half  text--right one-half">';
						echo '<h1 class="giga">Behold the beauty</h1>';
						echo '<h2 class="gamma">Furthermore, aenean nibh lorem, consequat congue <br/>lorem ipsum dolor sit amet</h2>';
					echo '</div>';	
				echo '</div>';	
			echo '</div>';	
    	echo '</li>';
    	echo '<li>';
      		echo '<img src="' . get_bloginfo('template_directory') . '/images/img-3.jpg" alt="">';
      		echo '<div class="centered--v--h soft--left row">';
	      		echo '<div class="grid">';
					echo '<div class="grid__item push--one-quarter  text--center one-half">';
						echo '<h1 class="giga">Aenean nibh Lorem</h1>';
						echo '<h2 class="gamma">Furthermore, aenean nibh lorem, consequat congue <br/>lorem ipsum dolor sit amet</h2>';
					echo '</div>';	
				echo '</div>';
			echo '</div>';
    	echo '</li>';
    echo '</ul>';
	echo '<nav class="slides-navigation">';
   		echo '<a href="#" class="next">Next</a>';
   		echo '<a href="#" class="prev">Previous</a>';
  	echo '</nav>';
echo '</div>';
echo '<section class="border--bottom islet ">';
	echo '<div class="row soft--top">';
		echo '<div class="grid">';
			echo '<div class="grid__item soft--top soft--bottom  one-third">';
				echo '<img class="img--circle" src="http://placehold.it/50x50">';
				echo '<h3>Contractor Installed</h3>';
				echo '<p>Aenean nibh lorem, consequat congue lorem ipsum dolor sit amet, consectetur adipiscing elit. In faucibus augue massa, vitae rhoncus urna rhoncus ac.</p>';
			echo '</div>';
			echo '<div class="grid__item soft--top soft--bottom  one-third">';
				echo '<img class="img--circle" src="http://placehold.it/50x50">';
				echo '<h3>Compatibility Checker</h3>';
				echo '<p>Aenean nibh lorem, consequat congue lorem ipsum dolor sit amet, consectetur adipiscing elit. In faucibus augue massa, vitae rhoncus urna rhoncus ac.</p>';
			echo '</div>';
			echo '<div class="grid__item soft--top soft--bottom  one-third">';
				echo '<img class="img--circle" src="http://placehold.it/50x50">';
				echo '<h3>Environmental Impact</h3>';
				echo '<p>Aenean nibh lorem, consequat congue lorem ipsum dolor sit amet, consectetur adipiscing elit. In faucibus augue massa, vitae rhoncus urna rhoncus ac.</p>';
			echo '</div>';
			echo '<div class="grid__item soft--top soft--bottom  one-third">';
				echo '<img class="img--circle" src="http://placehold.it/50x50">';
				echo '<h3>Energy Savigings Stats</h3>';
				echo '<p>Aenean nibh lorem, consequat congue lorem ipsum dolor sit amet, consectetur adipiscing elit. In faucibus augue massa, vitae rhoncus urna rhoncus ac.</p>';
			echo '</div>';
			echo '<div class="grid__item soft--top soft--bottom  one-third">';
				echo '<img class="img--circle" src="http://placehold.it/50x50">';
				echo '<h3>Box Contents</h3>';
				echo '<p>Aenean nibh lorem, consequat congue lorem ipsum dolor sit amet, consectetur adipiscing elit. In faucibus augue massa, vitae rhoncus urna rhoncus ac.</p>';
			echo '</div>';
			echo '<div class="grid__item soft--top soft--bottom  one-third">';
				echo '<img class="img--circle" src="http://placehold.it/50x50">';
				echo '<h3>Warranty & maintenance</h3>';
				echo '<p>Aenean nibh lorem, consequat congue lorem ipsum dolor sit amet, consectetur adipiscing elit. In faucibus augue massa, vitae rhoncus urna rhoncus ac.</p>';
			echo '</div>';
			

			
		echo '</div>';
	echo '</div>';
echo '</section>';
echo '<section class=" islet border--bottom ">';
	echo '<div class="row">';
		echo '<div class="grid">';
			echo '<div class="grid__item soft--top text--center one-whole">';
				echo '<h3>Heard enough?</h3>';
				echo '<h1 class="">Pre-order Your Ecobee</h1>';
				echo '<h2 class="gamma">Furthermore, aenean nibh lorem, consequat congue <br/>lorem ipsum dolor sit amet</h2>';
				echo '<a href="#" class="btn btn--large">Order Now</a>';
			echo '</div>';
		echo '</div>';
	echo '</div>';
echo '</section>';
echo '<section class="  islet ">';
	echo '<div class="row">';
		echo '<div class="grid">';
			echo '<div class="grid__item three-tenths soft--right relative">';
				echo '<h3>Smart Si Thermostat</h3>';
				echo '<p>Aenean nibh lorem, consequat congue lorem ipsum dolor sit amet.</p>';
				echo '<span class="icon-angle-right"></span>';
			echo '</div>';
			echo '<div class="grid__item  one-tenth">';
				echo '<img src="http://placehold.it/200x200">';
			echo '</div>';
			echo '<div class="grid__item one-tenth push--two-tenths">';
				echo '<img src="http://placehold.it/200x200">';
			echo '</div>';
			echo '<div class="grid__item  push--two-tenths relative soft--right three-tenths">';
				echo '<h3>Commercial Thermostat</h3>';
				echo '<p>Vivamus laoreet, mauris non euismod ornare, elit massa vestibulum lacus, at convallis elit elit quis sapien. </p>';
				echo '<span class="icon-angle-right"></span>';

			echo '</div>';
		echo '</div>';
	echo '</div>';	
echo '</section>';
get_footer();
echo '</div>';
get_template_part('part-drawer');
get_template_part('partials/foot');
?>